project_name: weblist
dist: .bin
builds:
  - id: weblist
    binary: "weblist"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    ldflags: "-s -w -X main.revision={{.Tag}}-{{.ShortCommit}}-{{.CommitDate}}"

archives:
  - id: tg-spam
    name_template: >-
      {{.ProjectName}}_
      {{- .Tag}}_
      {{- if eq .Os "darwin"}}macos
      {{- else if eq .Os "windows"}}win
      {{- else}}{{.Os}}{{end}}_
      {{- if eq .Arch "amd64"}}x86_64
      {{- else if eq .Arch "386"}}i386
      {{- else}}{{.Arch}}{{end}}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
    rlcp: true

brews:
  - name: weblist
    tap:
      owner: umputun
      name: homebrew-apps
      branch: master
    commit_author:
      name: umputun
      email: umputun@gmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://weblist.umputun.dev"
    description: "weblist is a self-hosted web service to access local files and folders"
    license: "MIT"

nfpms:
  - id: weblist
    package_name: weblist
    file_name_template: "{{.ProjectName}}_{{.Tag}}_{{.Os}}_{{.Arch}}"
    vendor: Umputun
    homepage: https://weblist.umputun.dev
    maintainer: Umputun <umputun@gmail.com>
    description: weblist is a self-hosted web service to access local files and folders
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    epoch: 1
    release: 1
