site_name: WEBLIST
site_url: https://weblist.umputun.dev/
site_author: Umputun
site_description: >-
  A modern, elegant file browser for the web.

repo_name: umputun/weblist
repo_url: https://github.com/umputun/weblist
copyright: Some rights reserved &copy; 2025 - umputun

theme:
  name: material
  custom_dir: overrides
  favicon: favicon.svg
  language: en
  palette:
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: black
      accent: white
  features:
    - navigation.instant
    - toc.follow
    - toc.integrate
    - content.code.annotate
    - navigation.sections
  logo: favicon.png

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - minify:
      minify_html: true

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/umputun
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/umputun/weblist/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/umputun
  analytics:
    provider: custom
    analytic_id: 9db03a56-ef6f-4c36-b73e-c058b8a29c11

markdown_extensions:
  - smarty
  - sane_lists
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Weblist: index.md